### ISSUE TITLE
找不到目录

### ISSUE THREAD

**Issue by WXS1-byte** [AaronSun2000/MakeupAttack#1]
<img width="703" alt="问题" src="https://github.com/user-attachments/assets/a0c6228e-1b97-49fd-908b-ef3ddcaa6637">

这个assets/pubfig-makeup\\train'目录在哪里，我把两个数据集都下载了也没找到呢

**Comment by AaronSun2000** [comment]
Thanks for your interest in our work. You can place the poisoned dataset downloaded from Google Drive in the "./assets/pubfig-makeup" folder. Of course, you can also change the folder name yourself, just match it with the code~
