### ISSUE TITLE
问题2

### ISSUE THREAD

**Issue by WXS1-byte** [AaronSun2000/MakeupAttack#3]
我想知道，直接培训之后，还用开始从零培训么，
<img width="1274" alt="1734593642900" src="https://github.com/user-attachments/assets/0726b542-7e96-4aee-a0c8-c2178b0a93d9" />
还是这几条命令依次执行

**Comment by AaronSun2000** [comment]
Hello！

Direct training and training from scratch are two different methods of operation. If you have already downloaded the malicious dataset we provided, you can proceed by following the instructions under the “Direct Training” section. On the other hand, if you wish to poison your own dataset and implement the corresponding backdoor attacks, you can follow the steps outlined in the “Training From Scratch” section.

In any case, you can choose either of these two approaches based on your preference.
