### ISSUE TITLE
模块找不到

### ISSUE THREAD

**Issue by WXS1-byte** [AaronSun2000/MakeupAttack#4]
faceutils包里的mask和dlib模块找不到
<img width="374" alt="af6176f3e4f16dcbb8c699e16ffa4b9" src="https://github.com/user-attachments/assets/97b328f0-5d1b-4400-9edf-05391c770f00" />
<img width="710" alt="e0026d08ddb1ad4430a0f797e88a704" src="https://github.com/user-attachments/assets/d1dc170b-307d-4c77-899f-6595606004fd" />

**Comment by AaronSun2000** [comment]
I have re-uploaded the relevant code. Please try running it and see if it works smoothly. Additionally, you may need to install the **_dlib_** library. For detailed installation instructions, please refer to [this link](https://github.com/CGCL-codes/AMT-GAN). If you have any further questions, please don't hesitate to ask, and I'll respond as soon as possible.

**Comment by WXS1-byte** [comment]
> 我已经重新上传了相关代码。请尝试运行它，看看它是否运行顺利。此外，您可能需要安装 **_dlib_** 库。详细的安装说明请参考[此链接](https://github.com/CGCL-codes/AMT-GAN)。如果您有任何其他问题，请随时提问，我会尽快回复。

您提供的这个新连接是我将https://github.com/AaronSun2000/MakeupAttack这个代码训练完成之后再进行下载和训练么

**Comment by AaronSun2000** [comment]
The link I provided is simply a suggestion for installing the required _dlib_ library, but you don't need to refer to it if you don't want to. Essentially, all you need to do is train my code to reproduce the results in the paper. If you have already downloaded the malicious dataset I provided, you can directly follow the command line in the "Direct Training" section to achieve the desired outcome.
