### ISSUE TITLE
找不到包

### ISSUE THREAD

**Issue by WXS1-byte** [AaronSun2000/MakeupAttack#7]
[
<img width="1280" alt="f37733ec0f8c6cd551aee3a557c7d97" src="https://github.com/user-attachments/assets/5b4d9a58-ec2d-4221-aa65-218061cfe098" />
](url)这个地方找不到main和它里面的方法
<img width="1280" alt="eed010c9b7e229948629d764465171f" src="https://github.com/user-attachments/assets/37a362dd-351b-485a-802e-95d91c06cdcf" />
还有一个是上次跟您提的mask这个问题好像还是有点不太对，望告知

**Comment by WXS1-byte** [comment]
<img width="647" alt="ee29811ea29b865eac4bb8dde8c9a32" src="https://github.com/user-attachments/assets/c7fc10c1-e4ee-4176-a728-c60026edc9e1" />
mask这个地方主要提示的是这个报错

**Comment by AaronSun2000** [comment]
We have made modifications to some files and re-uploaded them. Please check if the issue persists. If you have any questions, feel free to contact us at any time.
